"""Build the dependency licence inventory from installed package metadata.

Shipping installers means shipping other people's code, and the terms that come
with it. This reads what is actually installed rather than what a requirements
file hopes for, because the requirement pins a version and the *installed*
distribution is what carries the licence text.

Anything the environment does not have is reported as not installed rather than
guessed at. A licence inventory with a plausible-looking guess in it is worse
than one with a gap: the gap gets checked.

Run it with the release environment active:

    python tools/license_inventory.py --markdown > docs/dependency_licenses.md
"""

from __future__ import annotations

import argparse
import importlib.metadata as metadata
import json
import re
import sys
from pathlib import Path
from typing import Any, Iterable

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]

#: Requirement files that together describe a full installation.
REQUIREMENT_FILES = ("requirements.txt", "requirements-hrtf.txt")

_REQUIREMENT = re.compile(r"^\s*([A-Za-z0-9._-]+)")


def declared_requirements(root: Path | None = None) -> tuple[str, ...]:
    """Distribution names named by the requirement files, in order."""

    root = root or REPOSITORY_ROOT
    names: list[str] = []
    for filename in REQUIREMENT_FILES:
        path = root / filename
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or stripped.startswith("-"):
                continue
            match = _REQUIREMENT.match(stripped)
            if match and match.group(1) not in names:
                names.append(match.group(1))
    return tuple(names)


def _licence_of(distribution: metadata.Distribution) -> str:
    """The clearest licence statement the metadata offers.

    Modern wheels carry ``License-Expression``; older ones put an SPDX-ish name
    in ``License``, or the whole licence text, or say nothing and leave only a
    trove classifier. Preferring the short forms keeps the table readable, and
    falling back to the classifier keeps it populated.
    """

    fields = distribution.metadata
    expression = fields.get("License-Expression")
    if expression:
        return expression.strip()

    declared = (fields.get("License") or "").strip()
    if declared and "\n" not in declared and len(declared) <= 60:
        return declared

    classifiers = [
        value.split("::")[-1].strip()
        for value in (fields.get_all("Classifier") or [])
        if value.startswith("License ::")
    ]
    if classifiers:
        return "; ".join(classifiers)
    if declared:
        # A full licence text: quote its first meaningful line rather than the
        # whole thing, and say that is what happened.
        first = next((line.strip() for line in declared.splitlines() if line.strip()), "")
        return f"{first[:60]} (from full licence text)"
    return "unknown"


def inventory(names: Iterable[str] | None = None) -> list[dict[str, Any]]:
    """One record per declared dependency, installed or not."""

    records: list[dict[str, Any]] = []
    for name in names if names is not None else declared_requirements():
        try:
            distribution = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            records.append(
                {
                    "name": name,
                    "version": None,
                    "license": None,
                    "installed": False,
                    "homepage": None,
                }
            )
            continue
        fields = distribution.metadata
        records.append(
            {
                "name": fields.get("Name", name),
                "version": distribution.version,
                "license": _licence_of(distribution),
                "installed": True,
                "homepage": fields.get("Home-page") or fields.get("Project-URL"),
            }
        )
    return records


def copyleft(records: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    """Dependencies whose terms constrain how the whole may be distributed.

    Named rather than counted: a GPL dependency in a shipped installer is a
    decision about the licence of the product, and it should be made on purpose.
    """

    marks = ("gpl", "agpl", "copyleft")
    found = []
    for record in records:
        licence = (record.get("license") or "").lower()
        if any(mark in licence for mark in marks) and "lgpl" not in licence:
            found.append(record)
    return found


def as_markdown(records: list[dict[str, Any]]) -> str:
    lines = [
        "# Dependency licences",
        "",
        "Generated by `python tools/license_inventory.py --markdown`. Entries",
        "marked *not installed* were declared in a requirements file but absent",
        "from the environment this ran in; verify them in the release",
        "environment before shipping an installer.",
        "",
        "| Package | Version | Licence |",
        "|---|---|---|",
    ]
    for record in records:
        if record["installed"]:
            lines.append(
                f"| {record['name']} | {record['version']} | {record['license']} |"
            )
        else:
            lines.append(f"| {record['name']} | — | *not installed* |")

    restrictive = copyleft(records)
    lines += ["", "## Terms that constrain distribution", ""]
    if restrictive:
        for record in restrictive:
            lines.append(
                f"- **{record['name']} {record['version']}** is under "
                f"`{record['license']}`. Distributing a binary that links it "
                "carries that licence's obligations."
            )
    else:
        lines.append("- None found among the installed dependencies.")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--markdown", action="store_true", help="emit a Markdown table")
    arguments = parser.parse_args(argv)

    records = inventory()
    if arguments.markdown:
        print(as_markdown(records))
    else:
        json.dump(records, sys.stdout, indent=2)
        print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
